apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      nodePort: {{ .Values.service.nodePort }}